const int10000 = {precision: 'int', min: -10000, max: 10000}
const intFullRange = {precision: 'int', min: -32768, max: 32767}

export const dataTypes = {
    blue: intFullRange,
    green: intFullRange,
    red: intFullRange,
    nir: intFullRange,
    swir1: intFullRange,
    thermal: intFullRange,
    swir2: intFullRange,
    qa: intFullRange,
    thermal2: intFullRange,
    pan: intFullRange,
    aerosol: intFullRange,
    cirrus: intFullRange,
    data: intFullRange,
    redEdge1: intFullRange,
    redEdge2: intFullRange,
    redEdge3: intFullRange,
    redEdge4: intFullRange,
    waterVap: intFullRange,
    brightness: intFullRange,
    greenness: intFullRange,
    wetness: intFullRange,
    fourth: intFullRange,
    fifth: intFullRange,
    sixth: intFullRange,
    ndvi: int10000,
    ndmi: int10000,
    ndwi: int10000,
    mndwi: int10000,
    ndfi: intFullRange,
    evi: intFullRange,
    evi2: intFullRange,
    savi: intFullRange,
    nbr: int10000,
    ui: int10000,
    ndbi: int10000,
    ibi: intFullRange,
    nbi: intFullRange,
    ebbi: intFullRange,
    bui: intFullRange,
    dayOfYear: {precision: 'int', min: 0, max: 366},
    daysFromTarget: {precision: 'int', min: 0, max: 183}
}
