import React from 'react'

const typeFloat = {precision: 'float'}

export const dataTypes = () => ({
    VV: typeFloat,
    VV_min: typeFloat,
    VV_mean: typeFloat,
    VV_med: typeFloat,
    VV_max: typeFloat,
    VV_std: typeFloat,
    VV_cv: typeFloat,
    VVfit: typeFloat,
    VV_res: typeFloat,
    VVt: typeFloat,
    VV_phase: typeFloat,
    VV_amp: typeFloat,
    VH: typeFloat,
    VH_min: typeFloat,
    VH_mean: typeFloat,
    VH_med: typeFloat,
    VH_max: typeFloat,
    VH_std: typeFloat,
    VHfit: typeFloat,
    VH_res: typeFloat,
    VHt: typeFloat,
    VH_phase: typeFloat,
    VH_amp: typeFloat,
    VH_cv: typeFloat,
    ratio_VV_med_VH_med: typeFloat,
    NDCV: typeFloat,
    ratio_VV_VH: typeFloat,
    constant: typeFloat,
    dayOfYear: {precision: 'int', min: 0, max: 366},
    daysFromTarget: {precision: 'int', min: 0, max: 183},
})
