#!/usr/bin/env bash
docker rm -f sepal
DATA_LOCATION=$1
BACKUP_DATA_LOCATION=$2
BACKUP_IMAGE_LOCATION=$3
IMAGE_LOCATION=$4

cp -a $BACKUP_DATA_LOCATION/. $DATA_LOCATION/
sudo cp -a $BACKUP_IMAGE_LOCATION/. $IMAGE_LOCATION/