#!/bin/bash

export sandbox_user=$1
export ldap_host=$2
export ldap_admin_password=$3

function template {
    envsubst < $1 > $2
    chmod 0600 $2
}

template /templates/ldap.secret /etc/ldap.secret
template /templates/sssd.conf /etc/sssd/sssd.conf

ln -sf /etc/ldap.conf /etc/ldap/ldap.conf

rm /init_image.sh
#rm -rf /template

echo "$ldap_host ldap" >> /etc/hosts

/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
