#!/usr/bin/env bash

apt-get update && apt-get install -y wget software-properties-common curl unzip git maven

sudo apt-add-repository ppa:ansible/ansible
wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | apt-key add -
sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'


apt-get update && apt-get install -y jenkins ansible