const parameterSchema = require('./schema.json')
const {rules} = require('./rules')
const {getDefaults} = require('./defaults')

module.exports = {
    id: 'ASSET_MOSAIC',
    name: 'Asset',
    description: 'Wraps an EE Image or ImageCollection asset as a SEPAL recipe — visualizable, maskable, filterable, compositable, usable as input to other recipes, exportable. Only recipe that supports the ASSET_BOUNDS AOI variant.',
    useCases: [
        'Bring existing EE asset into SEPAL workflow',
        'Use published dataset (forest cover, land cover, surface water, DEM…) as input',
        'Apply masks/filters/compositing to external ImageCollection',
        'Wrap user-uploaded asset for reference from other recipes',
        'Reference global CCDC asset `projects/CCDC/v4` (not in GEE catalog — asset_search won\'t find it)'
    ],
    terms: [
        'asset', 'EE asset', 'Earth Engine asset', 'ImageCollection', 'custom asset', 'external imagery', 'third-party dataset', 'ASSET_BOUNDS',
        'Hansen', 'Global Forest Change', 'WorldCover', 'WorldCereal', 'Dynamic World', 'MODIS land cover', 'ESA CCI Land Cover',
        'JRC Surface Water', 'Global Surface Water', 'Global Mangrove Watch',
        'Satellite Embeddings', 'CCDC global', 'TerraClimate', 'CHIRPS',
        'SRTM', 'Copernicus DEM', 'GLO-30'
    ],
    chooseWhen: 'Points at an existing EE asset by id, names a published dataset, or wraps an uploaded asset. Use asset_search to resolve id from name.',
    dontChooseWhen: 'Wants imagery generated by SEPAL from satellite scenes — use MOSAIC (optical) or RADAR_MOSAIC (SAR).',
    outputs: 'Asset\'s own bands (asset-specific). Optional date/property filters, mask, and ImageCollection composite (MOSAIC, MEDIAN, MEAN, MIN, MAX, SD, MODE).',
    parameterSchema,
    rules,
    getDefaults,
    workflowSteps: [
        {id: 'aoi', name: 'Area of Interest', description: 'Define the geographic area (or use ASSET_BOUNDS for the asset\'s own geometry)', fields: ['aoi']},
        {id: 'assetDetails', name: 'Asset Details', description: 'Enter the Earth Engine asset path; type, bands, and metadata are loaded from EE', fields: ['assetDetails']},
        {id: 'dates', name: 'Date Filter', description: 'Optionally filter an ImageCollection by date (ALL_DATES, YEAR, or CUSTOM_DATE_RANGE)', fields: ['dates']},
        {id: 'filter', name: 'Filter', description: 'Optionally filter an ImageCollection by image properties (CLOUD_COVER, etc.)', fields: ['filter']},
        {id: 'mask', name: 'Mask', description: 'Optionally mask pixels by band-value constraints (per-image)', fields: ['mask']},
        {id: 'composite', name: 'Composite', description: 'How to reduce an ImageCollection to a single image (MOSAIC, MEDIAN, MEAN, MIN, MAX, SD, MODE)', fields: ['composite']}
    ],
    bands: {
        note: 'Band names are derived from the wrapped asset (assetDetails.bands[*].id)'
    },
    visualizations: [
        {note: 'Visualizations are derived from the wrapped asset (assetDetails.visualizations)'}
    ]
}
