#!/usr/bin/env bash
export AWS_ACCESS_KEY_ID='[SPECIFY]';
export AWS_SECRET_ACCESS_KEY='[SPECIFY]';
export SEPAL_MYSQL_ROOT_PASSWORD='[SPECIFY]'
export SEPAL_MYSQL_PASSWORD='[SPECIFY]'
export SEPAL_GEOSERVER_PASSWORD='[SPECIFY]'