#!/usr/bin/env bash

#script invoked by PHP backend to create user
#on the physical machine

USERNAME=$1
PASSWORD=$2
ASSIGNED_GROUP=$3
ENCRYPTED_PASSWD=${4:-false}


userExist=false
getent passwd ${USERNAME}  >/dev/null 2>&1 && userExist=true

if $userExist; then
    userId=$(id -u "$USERNAME")
else
    sudo -S useradd "$USERNAME" -s /bin/bash -m -d "/home/$USERNAME"
    if [ ! -z "$ASSIGNED_GROUP" ]; then
        sudo  -S usermod -aG "$ASSIGNED_GROUP" "$USERNAME"
    fi

    sudo -S usermod -aG ${USER_GROUP} ${USERNAME}


    if $ENCRYPTED_PASSWD; then
        echo "$USERNAME:$PASSWORD" | sudo  -S chpasswd --encrypted
    else
        echo "$USERNAME:$PASSWORD" | sudo  -S chpasswd
    fi



    userId=$(id -u "$USERNAME")


fi

echo $userId



