services:
  gateway-redis:
    extends:
      file: ../docker-compose.logger.yml
      service: logger
    image: "redis:6"
    container_name: gateway-redis
    volumes:
      - "${SEPAL_DATA_DIR}/gateway-redis:/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      timeout: 60s
      interval: 1s
      retries: 60
    networks:
      - sepal
    restart: always

  gateway:
    extends:
      file: ../docker-compose.logger.yml
      service: logger
    build:
      context: ../..
      dockerfile: ./modules/gateway/Dockerfile
      args:
        BUILD_NUMBER: "${BUILD_NUMBER}"
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/gateway:${SEPAL_VERSION:-latest}"
    container_name: gateway
    init: true
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      SEPAL_HOST: "${SEPAL_HOST}"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
    networks:
      - sepal
    extra_hosts:
      - 'host.docker.internal:${SEPAL_IP:-host-gateway}' # expose docker host ip address to container
    ulimits:
      core: 0
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      net.ipv4.tcp_keepalive_time: 60
      net.ipv4.tcp_keepalive_intvl: 60
      net.ipv4.tcp_keepalive_probes: 6
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
      timeout: 60s
      interval: 1s
      retries: 60
    restart: always

networks:
  sepal:
    external: true
