#!/bin/sh
# sshd AuthorizedKeysCommand: print the user's authorized public key(s) from the user module.
set -eu

user_url="${USER_URL:-http://user}"
[ -n "${1:-}" ] || exit 0

curl -s --max-time 10 --get --data-urlencode "username=$1" "${user_url}/auth/authorized-keys" || exit 0
