#!/usr/bin/env bash

entryPoint="org.openforis.sepal.sshgateway.NonInteractive"
if [ -z "$SSH_ORIGINAL_COMMAND" ]; then
    entryPoint="org.openforis.sepal.sshgateway.Interactive"
fi
sshScriptFile=$(mktemp /tmp/$USER-ssh.XXXXXX) > /dev/null 2>&1
chmod +x $sshScriptFile
password=$(cat /etc/sepalAdmin.passwd)
java \
    -cp /opt/sepal/bin/sepal-ssh-gateway.jar \
    "$entryPoint" \
    "$USER" \
    "http://sepal:1025/api/" \
    "/home/$USER/.ssh/id_rsa" \
    "$sshScriptFile" \
    "$password" 2> /dev/null

if [ -s $sshScriptFile ]; then
  n=0
  until [ "$n" -ge 5 ]
  do
    eval "$sshScriptFile \"${SSH_ORIGINAL_COMMAND:-}\"" && break
    n=$((n+1))
    sleep 5
  done
  rm $sshScriptFile > /dev/null 2>&1
fi
