#!/usr/bin/env bash
interactive="non-interactive"
if [ -z "$SSH_ORIGINAL_COMMAND" ]; then
    interactive="interactive"
fi
sshScriptFile=$(mktemp /tmp/$USER-ssh.XXXXXX) > /dev/null 2>&1
chmod +x $sshScriptFile
chmod 700 /home/${USER}/.ssh
chmod 644 /home/${USER}/.ssh/config
chmod 400 /home/${USER}/.ssh/id_rsa
chmod 644 /home/${USER}/.ssh/id_rsa.pub
cd /usr/local/src/sepal/modules/ssh-gateway
node src/main.js \
    --${interactive} \
    --username="${USER}" \
    --user-key-file="/home/${USER}/.ssh/id_rsa" \
    --endpoint="http://sepal:1025/api/" \
    --endpoint-password="$(cat /etc/sepalAdmin.passwd)" \
    --ssh-command-path="${sshScriptFile}"

if [ -s $sshScriptFile ]; then
  n=0
  until [ "$n" -ge 5 ]
  do
    eval "$sshScriptFile \"${SSH_ORIGINAL_COMMAND:-}\"" && break
    n=$((n+1))
    sleep 5
  done
  rm $sshScriptFile > /dev/null 2>&1
fi
