#!/usr/bin/env bash

runTask="runInteractive"
if [ -z "$SSH_ORIGINAL_COMMAND" ]; then
    runTask="runNonInteractive"
fi
sshScriptFile=$(mktemp /tmp/$USER-ssh.XXXXXX) > /dev/null 2>&1
chmod +x $sshScriptFile
password=$(cat /etc/sepalAdmin.passwd)
gradle :ssh-gateway:${runTask} \
    --args \
    "$USER" \
    "http://sepal:1025/api/" \
    "/home/$USER/.ssh/id_rsa" \
    "$sshScriptFile" \
    "$password" 2> /dev/null

if [ -s $sshScriptFile ]; then
  n=0
  until [ "$n" -ge 5 ]
  do
    eval "$sshScriptFile \"${SSH_ORIGINAL_COMMAND:-}\"" && break
    n=$((n+1))
    sleep 5
  done
  rm $sshScriptFile > /dev/null 2>&1
fi
