// TODO: Use msg for info
export const mathOptions = msg => [
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'abs', label: 'abs(', displayLabel: 'abs(x)', info: 'Returns the absolute value of the input.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'acos', label: 'acos(', displayLabel: 'acos(x)', info: 'Returns the arccosine of the input.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'asin', label: 'asin(', displayLabel: 'asin(x)', info: 'Returns the arcsine of the input.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'atan', label: 'atan(', displayLabel: 'atan(x)', info: 'Returns the arctangent of the input.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'atan2', label: 'atan2(', displayLabel: 'atan2(x, y)', info: 'Returns the arctangent of the quotient of its arguments.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'cbrt', label: 'cbrt(', displayLabel: 'cbrt(x)', info: 'Returns the cube root of the input.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'ceil', label: 'ceil(', displayLabel: 'ceil(x)', info: 'Returns the smallest integer greater than or equal to the input.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'cos', label: 'cos(', displayLabel: 'cos(x)', info: 'Returns the cosine of the input.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'cosh', label: 'cosh(', displayLabel: 'cosh(x)', info: 'Returns the hyperbolic cosine of the input.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'exp', label: 'exp(', displayLabel: 'exp(x)', info: 'Returns ex, where x is the argument, and e is Euler\'s number (2.718…, the base of the natural logarithm).', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'hypot', label: 'hypot(', displayLabel: 'hypot(x, y)', info: 'Returns the square root of the sum of squares of its arguments.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'log', label: 'log(', displayLabel: 'log(x)', info: 'Returns the natural logarithm (㏒e; also, ㏑) of the input.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'log10', label: 'log10(', displayLabel: 'log10(x)', info: 'Returns the base-10 logarithm of the input.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'max', label: 'max(', displayLabel: 'max(x, y)', info: 'Returns the largest of two numbers.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'min', label: 'min(', displayLabel: 'min(x, y)', info: 'Returns the smallest of two numbers.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'pow', label: 'pow(', displayLabel: 'pow(x, y)', info: 'Returns base x to the exponent power y (that is, xy).', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'random', label: 'random(', displayLabel: 'random(seed, distribution)', info: 'Generates a random number at each pixel location. When using the \'uniform\' distribution, outputs are in the range of [0, 1). Using the \'normal\' distribution, the outputs have μ=0, σ=1, but no explicit limits.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'round', label: 'round(', displayLabel: 'round(x)', info: 'Returns the value of the input rounded to the nearest integer.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'sin', label: 'sin(', displayLabel: 'sin(x)', info: 'Returns the sine of the input.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'sinh', label: 'sinh(', displayLabel: 'sinh(x)', info: 'Returns the hyperbolic sine of the input.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'sqrt', label: 'sqrt(', displayLabel: 'sqrt(x)', info: 'Returns the positive square root of the input.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'tan', label: 'tan(', displayLabel: 'tan(x)', info: 'Returns the tangent of the input.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathFunctions.section'), name: 'tanh', label: 'tanh(', displayLabel: 'tanh(x)', info: 'Returns the hyperbolic tangent of the input.', type: 'function'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathConstants.section'), name: 'E', label: 'E', info: 'Euler\'s number and the base of natural logarithms; approximately 2.718.', type: 'constant'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathConstants.section'), name: 'LN10', label: 'LN10', info: 'Natural logarithm of 10; approximately 2.303.', type: 'constant'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathConstants.section'), name: 'LN2', label: 'LN2', info: 'Natural logarithm of 2; approximately 0.693.', type: 'constant'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathConstants.section'), name: 'LOG10E', label: 'LOG10E', info: 'Base-10 logarithm of E; approximately 0.434.', type: 'constant'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathConstants.section'), name: 'LOG2E', label: 'LOG2E', info: 'Base-2 logarithm of E; approximately 1.443.', type: 'constant'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathConstants.section'), name: 'PI', label: 'PI', info: 'Ratio of a circle\'s circumference to its diameter; approximately 3.14159.', type: 'constant'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathConstants.section'), name: 'SQRT1_2', label: 'SQRT1_2', info: 'Square root of ½; approximately 0.707.', type: 'constant'},
    {section: msg('widget.codeEditor.eeAutoComplete.mathConstants.section'), name: 'SQRT2', label: 'SQRT2', info: 'Square root of 2; approximately 1.414.', type: 'constant'},
]

export const argCountByFunction = {
    abs: 1,
    acos: 1,
    asin: 1,
    atan: 1,
    atan2: 2,
    cbrt: 1,
    ceil: 1,
    cos: 1,
    cosh: 1,
    exp: 1,
    hypot: 2,
    log: 1,
    log10: 1,
    max: 2,
    min: 2,
    pow: 2,
    random: 2,
    round: 1,
    sin: 1,
    sinh: 1,
    sqrt: 1,
    tan: 1,
    tanh: 1,
}
