#!/usr/bin/env bash

apt-get update && apt-get install -y \
    wget \
    software-properties-common \
    curl \
    unzip \
    zip \
    git \
    python-setuptools \
    python-pip \
    apt-transport-https \
    fontconfig \
    fontconfig-config \
    rsync

export SDKMAN_DIR=/usr/local/lib/sdkman
curl -s https://get.sdkman.io | bash
source "$SDKMAN_DIR/bin/sdkman-init.sh"
yes | sdk install java 11.0.11.hs-adpt
sdk install groovy
sdk install maven
sdk install gradle 6.1 # Gradle 7 requires updates to build scripts
echo 'source "$SDKMAN_DIR/bin/sdkman-init.sh"' >> /etc/profile
echo "JAVA_HOME=\"/usr/local/lib/sdkman/candidates/java/current\"" >> /etc/environment

#install ansible and jenkins
wget -qO - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -
sudo apt-add-repository -y ppa:ansible/ansible
sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
#wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | apt-key add -
#sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'

apt-get update && apt-get install -y jenkins ansible

pip2 install boto six
