#!/usr/bin/env bash
set -e

# Needed for apt-add-repository command
apt-get -y update && apt-get install -y \
  curl \
  software-properties-common \
  sudo \
  ca-certificates \
  gnupg \
  lsb-release

curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
apt-get update && apt-get install -y nodejs\
 bzip2

useradd -m -d "${JENKINS_HOME}"  jenkins
useradd -m -d /home/github github

chown -R jenkins /usr/share/jenkins/ref

chmod +x /downloads
chmod +x /init_container
chmod +x /jenkins.sh

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update && apt-get install -y docker-ce-cli

VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*\d')
DESTINATION=/usr/local/bin/docker-compose # Maybe not in PATH of root..
sudo curl -L https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-$(uname -s)-$(uname -m) -o $DESTINATION
sudo chmod 755 $DESTINATION
