services:
  sys-monitor:
    extends:
      file: ../docker-compose.logger.override.yml
      service: logger
    volumes:  # To allow dynamic reloading in dev
      - ${SEPAL_PROJECT_DIR}/modules/sys-monitor/lib/shared:/usr/local/src/sepal/lib/js/shared
      - ${SEPAL_PROJECT_DIR}/lib/js/shared/src:/usr/local/src/sepal/lib/js/shared/src
      - ${SEPAL_PROJECT_DIR}/lib/js/shared/package.json:/usr/local/src/sepal/lib/js/shared/package.json
      # - ${SEPAL_PROJECT_DIR}/lib/js/shared:/usr/local/src/sepal/lib/js/shared
      - ${SEPAL_PROJECT_DIR}/modules/sys-monitor:/usr/local/src/sepal/modules/sys-monitor
