- name: Build Operations server
  hosts: "tag_Type_Operations"
  user: ubuntu
  become: yes
  gather_facts: true

  vars_files:
    - vars/vars.yml
    - "{{ secret_vars_file }}"

  pre_tasks:
    - name: Copy Jenkins Image
      copy: src="../../../modules/jenkins/" dest="/opt/sepal/modules/jenkins/"

    - name: Create docker-registry certificate dir
      file:
        path: "/etc/docker/certs.d/{{ docker_repository_host }}"
        state: directory
    - name: Copy docker-registry certificate
      copy:
        src: ~/.sepal/certificates/docker-registry.crt
        dest: "/etc/docker/certs.d/{{ docker_repository_host }}/ca.crt"

    - name: Create ELK certificate dir
      file:
        path: "/data/elk/certificates"
        state: directory
    - name: Copy ELK certificates
      copy: src={{ item }} dest=/data/elk/certificates owner=root mode=644
      with_fileglob:
        - ~/.sepal/certificates/elk*

  roles:
    - role: unattended-upgrades
      unattended_origins_patterns:
        - 'origin=Ubuntu,archive=${distro_codename}-security'
        - 'o=Ubuntu,a=${distro_codename}-updates'

    - { role: docker, users: ['ubuntu'] }
    - { role: docker-registry }
    - { role: ansible }

    - { role: build-module, module: jenkins }
    - { role: build-module, module: elk }
    - { role: build-module, module: nginx }

    - { role: run-module, module: jenkins }
    - { role: run-module, module: elk }
    - { role: run-module, module: nginx }

  post_tasks:
    - name: "Clean environment"
      file:
        path: /opt/sepal
        state: absent

    - name: "Create symlink to /opt/sepal"
      file:
        src: "/data/jenkins/workspace/Sepal"
        path: "/opt/sepal"
        state: "link"
        force: "yes"

