// Default classChange model. Mirrors the GUI's `defaultModel` from
// classChangeRecipe.js, with two corrections:
//
//   - `options` is left empty rather than including `cloudThreshold` and
//     `shadowThreshold`. Those two fields appear in the GUI's defaultModel
//     but are NOT read by the EE backend and NOT exposed by the Options
//     panel — they're dead state from an earlier recipe layout. Schema-as-
//     truth says the schema rejects unknown fields; tracking the dead ones
//     in defaults would just propagate the bug.
//
//   - `legend` is left absent. It's auto-generated by the GUI from the
//     cartesian product of fromImage.legendEntries x toImage.legendEntries
//     once both inputs are selected; manufacturing it here would conflict
//     with whatever the GUI later synthesizes.
//
// `fromImage` and `toImage` are intentionally absent — there's no sensible
// default for either; the LLM must populate them based on user intent.

const getDefaults = () => {
    const year = new Date().getUTCFullYear()
    return {
        dates: {
            fromDate: `${year}-01-01`,
            toDate: `${year + 1}-01-01`
        },
        options: {}
    }
}

module.exports = {getDefaults}
