#!/usr/bin/expect

spawn /data/sepal/pull_sandbox.sh
expect "Username"
send "{{ docker_username }}\n"
expect "Password"
send "{{ docker_password }}\n"
expect "Email"
send "{{ docker_email }}\n"
interact
