#!/usr/bin/env bash

username=$1
password=$2

logFile=/var/log/supervisor/change-sepal-user-password.log

ldappasswd -p 389 -h ldap -x -D cn=admin,dc=sepal,dc=org -w "$(cat /etc/ldap.secret)" \
    -s "$password" uid=$username,ou=People,dc=sepal,dc=org -ZZ >> $logFile 2>&1