# -*- mode: ruby -*-
# vi: set ft=ruby :

project_dir = '../../..'

Vagrant.configure(2) do |config|
  config.vm.network 'private_network', ip: "#{ENV['VAGRANT_IP']}"
  config.vm.box = 'ubuntu/trusty64'
  config.disksize.size = "64GB"
  config.vm.synced_folder project_dir, '/opt/sepal/'

  config.vm.provider 'virtualbox' do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'deploy.yml'
    #ansible.verbose = 'vvvv'
    ansible.extra_vars = {
        ansible_ssh_user: 'vagrant',
        deploy_environment: 'DEV',
        secret_vars_file: "#{ENV['CONFIG_HOME']}/secret.yml",
        docker_repository_host: 'localhost',
        version: '1',
        vagrant_ip: "#{ENV['VAGRANT_IP']}",
        config_home:"#{ENV['CONFIG_HOME']}",
        restore_backup: false
    }
  end

end
