# -*- mode: ruby -*-
# vi: set ft=ruby :

project_dir = '../../..'

Vagrant.configure(2) do |config|
  config.vm.network 'private_network', ip: '172.28.128.3'
  config.vm.box = 'ubuntu/trusty64'
  config.vm.synced_folder project_dir, '/opt/sepal/'

  config.vm.provider 'virtualbox' do |v|
    v.memory = 4096
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'deploy.yml'
    #ansible.verbose = 'vvvv'
    ansible.extra_vars = {
        ansible_ssh_user: 'vagrant',
        deploy_environment: 'Staging',
        local_sepal: false,
        local_php: true,
        secret_vars_file: '~/.sepal/secret.yml',
        docker_repository_host: 'localhost',
        version: '1',
        use_custom_host: true,
        custom_host: '172.28.128.3'
    }
  end

end
