services:
  gui:
    extends:
      file: ../docker-compose.logger.override.yml
      service: logger
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/gui:dev"
    build:
      target: build
    user: "1000:1000"
    volumes:
      - ${SEPAL_PROJECT_DIR}/modules/gui:/usr/local/src/sepal/modules/gui # To allow dynamic reloading in dev
