server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /usr/local/src/sepal/modules/gui/dist;
    server_tokens off;

    index index.html;

    server_name _;

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;

    location = / {
        try_files $uri $uri/ /;
    }

    location /- {
        try_files $uri $uri/ /;
    }

    location /reset-password {
        try_files $uri $uri/ /;
    }

    location /setup-account {
        try_files $uri $uri/ /;
    }

    location /assets {
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }

    location /resource {
        add_header Cache-Control "public, max-age=86400";
        try_files $uri =404;
    }
}