#!/usr/bin/env bash
set -e

username=$1
password=$2

ldappasswd -p 389 -h ldap -x -D cn=admin,dc=sepal,dc=org -w "$(cat /etc/ldap.secret)" \
    -s "$password" uid=$username,ou=People,dc=sepal,dc=org -ZZ