- name: Configure Sepal instance
  hosts: "tag_Type_Sepal:&tag_Environment_{{ deploy_environment }}"
  user: ec2-user
  become: yes
  gather_facts: true

  vars_files:
    - "{{ secret_vars_file }}"

  pre_tasks:
    - set_fact:
        ldap_host: "{{ ec2_private_ip_address }}"
        syslog_host: "{{ ec2_private_ip_address }}"
        elk_host: "{{ elk_host }}"
        syslog_address: "unixgram:///dev/log"

    - file: path="/data/sepal/etc" state=directory
    - template: src="./aws.properties" dest=/data/sepal/etc/aws.properties

    # rsyslog
    - name: Copy rsyslog.conf
      template: src="rsyslog.conf" dest=/etc/rsyslog.conf

    - name: Start rsyslog
      service: name=rsyslog state=started

    # docker
    - file: path="/data/docker/storage/devicemapper/metadata" state=directory
    - file: path="/data/docker/storage/tmp" state=directory

    - name: Create Docker LVM Volume Group
      lvg: vg=vg-docker pvs=/dev/sdb

    - name: Create Docker LVM Data Volume
      lvol: vg=vg-docker lv=data size=30g

    - name: Create Docker LVM Metadata Volume
      lvol: vg=vg-docker lv=metadata size=19g

    - name: Create docker-registry certificate dir
      file:
        path: "/etc/docker/certs.d/{{ docker_repository_host }}"
        state: directory

    - name: Copy docker-registry certificate
      copy:
        src: "{{ config_home }}/certificates/docker-registry.crt"
        dest: "/etc/docker/certs.d/{{ docker_repository_host }}/ca.crt"

    - name: Install docker
      command: "amazon-linux-extras install docker"

    - name: Install pip
      yum:
        name: "python-pip"

    - name: Install docker-compose
      pip:
        name: docker-compose

    - name: Create /etc/docker
      file:
        path: "/etc/docker"
        state: directory

    - name: Copy /etc/docker/daemon.json
      copy: src=docker-daemon.json dest=/etc/docker/daemon.json

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker

    - name: Enable docker
      systemd:
        name: docker
        state: started
        enabled: yes
        masked: no

  roles:
    - { role: aws-mount-efs }
    - { role: docker-login }

    - { role: run-module, module: backup }
    - { role: run-module, module: kafka }
    - { role: run-module, module: ldap }
    - { role: run-module, module: ldap-backup }
    - { role: run-module, module: mysql }
    - { role: run-module, module: mysql-backup }
    - { role: run-module, module: google-earth-engine}
    - { role: run-module, module: user }
    - { role: run-module, module: sepal-server, container_name: sepal }
    - { role: run-module, module: gui }
    - { role: run-module, module: ceo }
    - { role: run-module, module: peatlands }
    - { role: run-module, module: ssh-gateway }
    - { role: run-module, module: gateone }
    - { role: run-module, module: api-gateway }
    - { role: run-module, module: letsencrypt }
    - { role: run-module, module: haproxy }
