- name: Provision Sepal
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Create Sepal security group
      ec2_group:
        name: "Sepal"
        description: The Sepal Security Group
        region: "{{ lookup('env', 'AWS_REGION') }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 168.202.0.0/16
            rule_desc: 'FAO'
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            rule_desc: 'HTTP'
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
            rule_desc: 'HTTPS'
          - proto: udp
            from_port: 514
            to_port: 514
            cidr_ip: 172.31.0.0/16
            rule_desc: 'syslog'
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: 172.31.0.0/16
            rule_desc: 'Subnet'
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ local_ip_address }}/32"
            rule_desc: 'Deployer'
        rules_egress:
          - proto: all
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0

    - name: Create Sepal network interface
      amazon.aws.ec2_eni:
        name: "Sepal {{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
        region: "{{ lookup('env', 'AWS_REGION') }}"
        subnet_id: "{{ lookup('env', 'AWS_SUBNET_ID') }}"
        security_groups: 
          - "Sepal"
          - "Sepal-Swarm"
          - "Sepal-Swarm-Manager"
          - "Sepal-Developers"
        allow_reassignment: true
        secondary_private_ip_address_count: 1
        delete_on_termination: true
      register: sepal_eni

    - name: Create Sepal instance
      ec2_instance:
        key_name: "{{ lookup('env', 'AWS_REGION') }}"
        instance_type: "{{ lookup('env', 'AWS_INSTANCE_TYPE') }}"
        image_id: "{{ lookup('env', 'AWS_AMI') }}"
        region: "{{ lookup('env', 'AWS_REGION') }}"
        availability_zone: "{{ lookup('env', 'AWS_AVAILABILITY_ZONE') }}"
        state: running
        wait: true
        exact_count: 1
        filters:
          tag:Type: Sepal
          tag:Environment: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
          instance-state-name: running
        purge_tags: false
        tags:
          Name: "Sepal - {{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
          Type: Sepal
          Environment: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
        network:
          interfaces:
            - id: "{{ sepal_eni.interface.id }}" 
        ebs_optimized: true
        volumes:
          - device_name: /dev/xvda
            ebs:
              delete_on_termination: false
              volume_type: gp3
              volume_size: 10
          - device_name: /dev/sdf # /data
            ebs:
              delete_on_termination: false
              volume_type: gp3
              volume_size: 200
          - device_name: /dev/sdg # /var/lib/docker
            ebs:
              delete_on_termination: false
              volume_type: gp3
              volume_size: 50
          - device_name: /dev/sdh # /var/log
            ebs:
              delete_on_termination: false
              volume_type: gp3
              volume_size: 10

    - name: Get Sepal instance information
      ec2_instance_info:
        region: "{{ lookup('env', 'AWS_REGION') }}"
        filters:
          tag:Type: "Sepal"
          tag:Environment: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
          instance-state-name: running
      register: ec2_sepal

    # Assign Sepal Instance Volume tags

    - name: Tag Sepal instance volumes (1/4)
      amazon.aws.ec2_tag:
        region: "{{ lookup('env', 'AWS_REGION') }}"
        resource: "{{ ec2_sepal.instances[0].block_device_mappings[0].ebs.volume_id }}"
        tags:
          Name: "Sepal {{ lookup('env', 'DEPLOY_ENVIRONMENT') }} Root"

    - name: Tag Sepal instance volumes (2/4)
      amazon.aws.ec2_tag:
        region: "{{ lookup('env', 'AWS_REGION') }}"
        resource: "{{ ec2_sepal.instances[0].block_device_mappings[1].ebs.volume_id }}"
        tags:
          Name: "Sepal {{ lookup('env', 'DEPLOY_ENVIRONMENT') }} Data"

    - name: Tag Sepal instance volumes (3/4)
      amazon.aws.ec2_tag:
        region: "{{ lookup('env', 'AWS_REGION') }}"
        resource: "{{ ec2_sepal.instances[0].block_device_mappings[2].ebs.volume_id }}"
        tags:
          Name: "Sepal {{ lookup('env', 'DEPLOY_ENVIRONMENT') }} Docker"

    - name: Tag Sepal instance volumes (4/4)
      amazon.aws.ec2_tag:
        region: "{{ lookup('env', 'AWS_REGION') }}"
        resource: "{{ ec2_sepal.instances[0].block_device_mappings[3].ebs.volume_id }}"
        tags:
          Name: "Sepal {{ lookup('env', 'DEPLOY_ENVIRONMENT') }} Log"

    - name: Wait for SSH to be available on Sepal
      local_action: wait_for host="{{ item.public_ip_address }}"
                    port=22
                    state="started"
      with_items: "{{ ec2_sepal.instances }}"
      no_log: true
