- name: Provision Sepal-Storage
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Create Sepal-Storage security group
      ec2_group:
        name: "Sepal-Storage"
        description: The Sepal-Storage Security Group
        region: "{{ lookup('env', 'AWS_REGION') }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 168.202.0.0/16
            rule_desc: 'FAO'
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ local_ip_address }}/32"
            rule_desc: 'Deployer'
        rules_egress:
          - proto: all
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0
      register: sepal_storage_group

    - name: Create Sepal-Storage instance
      ec2_instance:
        key_name: "{{ lookup('env', 'AWS_REGION') }}"
        instance_type: m5a.large
        image_id: "{{ lookup('env', 'AWS_AMI') }}"
        region: "{{ lookup('env', 'AWS_REGION') }}"
        availability_zone: "{{ lookup('env', 'AWS_AVAILABILITY_ZONE') }}"
        state: started
        wait: true
        filters:
          tag:Name: "Sepal-Storage - {{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
          tag:Type: "SepalStorage"
          tag:Environment: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
          instance-state-name: running
        exact_count: 1
        purge_tags: false
        tags:
          Type: "SepalStorage"
          Environment: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
        volumes:
          - device_name: /dev/xvda
            ebs:
              delete_on_termination: false
              volume_type: gp3
              volume_size: 32
          - device_name: /dev/sdb
            ebs:
              delete_on_termination: false
              volume_type: gp3
              volume_size: 32
      register: started_ec2_sepal_storage

    - name: Get Sepal-Storage instance information
      ec2_instance_info:
        region: "{{ lookup('env', 'AWS_REGION') }}"
        filters:
          tag:Type: "SepalStorage"
          tag:Environment: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
          instance-state-name: running
      register: ec2_sepal_storage

    - name: Assign Sepal-Storage security groups
      amazon.aws.ec2_eni:
        name: "Sepal-Storage {{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
        region: "{{ lookup('env', 'AWS_REGION') }}"
        subnet_id: "{{ lookup('env', 'AWS_SUBNET_ID') }}"
        eni_id: "{{ ec2_sepal_storage.instances[0].network_interfaces[0].network_interface_id }}"
        security_groups: 
          - "Sepal-Storage"
          - "Sepal-Swarm"
          - "Sepal-Developers"

    - name: Wait for SSH to be available on Sepal-Storage
      local_action: wait_for host="{{ item.public_ip_address }}"
                    port=22
                    state="started"
      with_items: "{{ ec2_sepal_storage.instances }}"
      no_log: true
