- name: Provision Sepal-Apps
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Get Sepal instance information
      ec2_instance_info:
        region: "{{ lookup('env', 'AWS_REGION') }}"
        filters:
          tag:Type: "Sepal"
          tag:Environment: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
          instance-state-name: running
      register: ec2_sepal

    - set_fact:
        SEPAL_PUBLIC_IP: "{{ ec2_sepal.instances[0].public_ip_address }}"

    - name: Create Sepal-Apps security group
      ec2_group:
        name: "Sepal-Apps"
        description: The Sepal-Apps Security Group
        region: "{{ lookup('env', 'AWS_REGION') }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "{{ SEPAL_PUBLIC_IP }}/32"
            rule_desc: 'Sepal'
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 168.202.0.0/16
            rule_desc: 'FAO'
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ local_ip_address }}/32"
            rule_desc: 'Deployer'
        rules_egress:
          - proto: all
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0
      register: sepal_apps_group

    - name: Create Sepal-Apps instance
      ec2_instance:
        key_name: "{{ lookup('env', 'AWS_REGION') }}"
        instance_type: t3a.medium
        image_id: "{{ lookup('env', 'AWS_AMI') }}"
        region: "{{ lookup('env', 'AWS_REGION') }}"
        availability_zone: "{{ lookup('env', 'AWS_AVAILABILITY_ZONE') }}"
        state: running
        wait: true
        exact_count: 1
        filters:
          tag:Type: "SepalApps"
          tag:Environment: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
          instance-state-name: running
        purge_tags: false
        tags:
          Name: "Sepal-Apps - {{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
          Type: SepalApps
          Environment: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
        ebs_optimized: true
        volumes:
          - device_name: /dev/xvda
            ebs:
              delete_on_termination: false
              volume_type: gp3
              volume_size: 32
          - device_name: /dev/sdb
            ebs:
              delete_on_termination: false
              volume_type: gp3
              volume_size: 32
      register: ec2_sepal_apps

    - name: Assign Sepal-Apps security groups
      amazon.aws.ec2_eni:
        name: "Sepal-Apps {{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
        region: "{{ lookup('env', 'AWS_REGION') }}"
        subnet_id: "{{ lookup('env', 'AWS_SUBNET_ID') }}"
        eni_id: "{{ ec2_sepal_apps.instances[0].network_interfaces[0].network_interface_id }}"
        security_groups: 
          - "Sepal-Apps"
          - "Sepal-Developers"

    - name: Get Sepal-Apps instance information
      ec2_instance_info:
        region: "{{ lookup('env', 'AWS_REGION') }}"
        filters:
          tag:Type: "SepalApps"
          tag:Environment: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
          instance-state-name: running
      register: ec2_sepal_apps

    - set_fact:
        SEPAL_APPS_PUBLIC_IP: "{{ ec2_sepal_apps.instances[0].public_ip_address }}"

    - name: Add DNS entry for Sepal-Apps instance
      amazon.aws.route53:
        state: present
        zone: "{{ lookup('env', 'AWS_ROUTE_53_ZONE') }}"
        record: "{{ lookup('env', 'SEPAL_APPS_HOST') }}"
        type: A
        value: "{{ SEPAL_APPS_PUBLIC_IP }}"
        overwrite: true
        wait: true
            
    - name: Wait for SSH to be available on Sepal-Apps
      local_action: wait_for host="{{ item.public_ip_address }}"
                    port=22
                    state="started"
      with_items: "{{ ec2_sepal_apps.instances }}"
      no_log: true
