#!/usr/bin/env bash

apt-get update && apt-get install -y \
    wget \
    software-properties-common \
    curl \
    unzip \
    zip \
    git \
    python-setuptools \
    apt-transport-https

export SDKMAN_DIR=/usr/local/lib/sdkman
curl -s get.sdkman.io | bash
source "$SDKMAN_DIR/bin/sdkman-init.sh"
yes | sdk install java 8u161-oracle
sdk install groovy
sdk install maven
echo 'source "$SDKMAN_DIR/bin/sdkman-init.sh"' >> /etc/profile
echo "JAVA_HOME=\"/usr/local/lib/sdkman/candidates/java/current\"" >> /etc/environment

#install ansible and jenkins
sudo apt-add-repository ppa:ansible/ansible
wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | apt-key add -
sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'

apt-get update && apt-get install -y jenkins ansible

easy_install pip
pip install boto six
