#!/usr/bin/env bash
set -e

# Needed for apt-add-repository command
apt-get -y update && apt-get install -y \
  curl \
  software-properties-common \
  sudo

curl -sL https://deb.nodesource.com/setup_14.x | bash -
apt-get install -y nodejs\
 bzip2

useradd -m -d "${JENKINS_HOME}"  jenkins
useradd -m -d /home/github github

chown -R jenkins /usr/share/jenkins/ref

chmod +x /downloads
chmod +x /init_container
chmod +x /jenkins.sh


