#!/usr/bin/env bash

if [ ! -z "$JENKINS_PASSWD" ]; then
echo "jenkins:$JENKINS_PASSWD" | chpasswd
fi

if [ ! -z "$GITHUB_ACCOUNT_PASSWD" ]; then
echo "github:$GITHUB_ACCOUNT_PASSWD" | chpasswd
fi

ln -s ${JENKINS_HOME}/workspace/Sepal /opt/sepal

rm -rf ${JENKINS_HOME}/jobs/Sepal/config.xml

exec /jenkins.sh
