services:
  ai:
    extends:
      file: ../docker-compose.logger.override.yml
      service: logger
    environment:
      LLM_PROVIDER: "lmstudio"
      LLM_API_KEY: "none"
      LLM_MODEL: "qwen/qwen3.5-9b"
      LLM_BASE_URL: "http://llmster:1234/v1"
    volumes:  # To allow dynamic reloading in dev
      # lib/shared
      - ${SEPAL_PROJECT_DIR}/lib/js/shared/src:/usr/local/src/sepal/lib/js/shared/src
      - ${SEPAL_PROJECT_DIR}/lib/js/shared/package.json:/usr/local/src/sepal/lib/js/shared/package.json
      - ${SEPAL_PROJECT_DIR}/modules/ai/lib/shared/package-lock.json:/usr/local/src/sepal/lib/js/shared/package-lock.json
      - ${SEPAL_PROJECT_DIR}/modules/ai/lib/shared/node_modules:/usr/local/src/sepal/lib/js/shared/node_modules
      # module
      - ${SEPAL_PROJECT_DIR}/modules/ai:/usr/local/src/sepal/modules/ai
