services:
  sepal-dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - DOCKER_GID=${DOCKER_GID}
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
    image: sepal-dev
    tty: true
    stdin_open: true
    container_name: sepal-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host:ro
      - ..:/home/sepal/sepal
      - ${SEPAL_CONFIG:-~/.sepal}:/etc/sepal/config
    networks:
      - sepal
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}

networks:
  sepal:
    external: true
    name: sepal
