services:
  sepal-dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
    image: sepal-dev
    tty: true
    stdin_open: true
    container_name: sepal-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/usr/local/src/sepal
      - ${SEPAL_CONFIG:-~/.sepal}:/etc/sepal/config
    networks:
      - sepal

networks:
  sepal:
    external: true
    name: sepal
