/**
 * @author Mino Togna
 */

var countries = [
    { "data": "AFG", "value": "Afghanistan" },
    { "data": "ALB", "value": "Albania" },
    { "data": "DZA", "value": "Algeria" },
    { "data": "ASM", "value": "American Samoa" },
    { "data": "AND", "value": "Andorra" },
    { "data": "AGO", "value": "Angola" },
    { "data": "ATG", "value": "Antigua and Barbuda" },
    { "data": "ARG", "value": "Argentina" },
    { "data": "ARM", "value": "Armenia" },
    { "data": "ABW", "value": "Aruba" },
    { "data": "AUS", "value": "Australia" },
    { "data": "AUT", "value": "Austria" },
    { "data": "AZE", "value": "Azerbaijan, Republic of" },
    { "data": "BHS", "value": "Bahamas" },
    { "data": "BHR", "value": "Bahrain" },
    { "data": "BGD", "value": "Bangladesh" },
    { "data": "BRB", "value": "Barbados" },
    { "data": "BLR", "value": "Belarus" },
    { "data": "BEL", "value": "Belgium" },
    { "data": "BLZ", "value": "Belize" },
    { "data": "BEN", "value": "Benin" },
    { "data": "BMU", "value": "Bermuda" },
    { "data": "BTN", "value": "Bhutan" },
    { "data": "BOL", "value": "Bolivia" },
    { "data": "BIH", "value": "Bosnia and Herzegovina" },
    { "data": "BWA", "value": "Botswana" },
    { "data": "BRA", "value": "Brazil" },
    { "data": "VGB", "value": "British Virgin Islands" },
    { "data": "BRN", "value": "Brunei Darussalam" },
    { "data": "BGR", "value": "Bulgaria" },
    { "data": "BFA", "value": "Burkina Faso" },
    { "data": "BDI", "value": "Burundi" },
    { "data": "KHM", "value": "Cambodia" },
    { "data": "CMR", "value": "Cameroon" },
    { "data": "CAN", "value": "Canada" },
    { "data": "CPV", "value": "Cape Verde" },
    { "data": "CYM", "value": "Cayman Islands" },
    { "data": "CAF", "value": "Central African Republic" },
    { "data": "TCD", "value": "Chad" },
    { "data": "CHL", "value": "Chile" },
    { "data": "CHN", "value": "China" },
    { "data": "COL", "value": "Colombia" },
    { "data": "COM", "value": "Comoros" },
    { "data": "COK", "value": "Cook Islands" },
    { "data": "CRI", "value": "Costa Rica" },
    { "data": "CIV", "value": "Côte d'Ivoire" },
    { "data": "HRV", "value": "Croatia" },
    { "data": "CUB", "value": "Cuba" },
    { "data": "CYP", "value": "Cyprus" },
    { "data": "CZE", "value": "Czech Republic" },
    { "data": "COD", "value": "Congo, Dem Republic of" },
    { "data": "DNK", "value": "Denmark" },
    { "data": "DJI", "value": "Djibouti" },
    { "data": "DOM", "value": "Dominican Republic" },
    { "data": "DMA", "value": "Dominica" },
    { "data": "ECU", "value": "Ecuador" },
    { "data": "EGY", "value": "Egypt" },
    { "data": "SLV", "value": "El Salvador" },
    { "data": "GNQ", "value": "Equatorial Guinea" },
    { "data": "ERI", "value": "Eritrea" },
    { "data": "EST", "value": "Estonia" },
    { "data": "ETH", "value": "Ethiopia" },
    { "data": "FRO", "value": "Faroe Islands" },
    { "data": "FJI", "value": "Fiji Islands" },
    { "data": "FIN", "value": "Finland" },
    { "data": "FRA", "value": "France" },
    { "data": "GUF", "value": "French Guiana" },
    { "data": "PYF", "value": "French Polynesia" },
    { "data": "GAB", "value": "Gabon" },
    { "data": "GMB", "value": "Gambia" },
    { "data": "GEO", "value": "Georgia" },
    { "data": "DEU", "value": "Germany" },
    { "data": "GHA", "value": "Ghana" },
    { "data": "GRC", "value": "Greece" },
    { "data": "GRD", "value": "Grenada" },
    { "data": "GLP", "value": "Guadeloupe" },
    { "data": "GUM", "value": "Guam" },
    { "data": "GTM", "value": "Guatemala" },
    { "data": "GNB", "value": "Guinea-Bissau" },
    { "data": "GIN", "value": "Guinea" },
    { "data": "GUY", "value": "Guyana" },
    { "data": "HTI", "value": "Haiti" },
    { "data": "HND", "value": "Honduras" },
    { "data": "HUN", "value": "Hungary" },
    { "data": "ISL", "value": "Iceland" },
    { "data": "IND", "value": "India" },
    { "data": "IDN", "value": "Indonesia" },
    { "data": "IRN", "value": "Iran, Islamic Rep of" },
    { "data": "IRQ", "value": "Iraq" },
    { "data": "IRL", "value": "Ireland" },
    { "data": "IMN", "value": "Isle of Man" },
    { "data": "ISR", "value": "Israel" },
    { "data": "ITA", "value": "Italy" },
    { "data": "JAM", "value": "Jamaica" },
    { "data": "JPN", "value": "Japan" },
    { "data": "JOR", "value": "Jordan" },
    { "data": "KAZ", "value": "Kazakhstan" },
    { "data": "KEN", "value": "Kenya" },
    { "data": "KIR", "value": "Kiribati" },
    { "data": "KWT", "value": "Kuwait" },
    { "data": "KGZ", "value": "Kyrgyzstan" },
    { "data": "LAO", "value": "Laos" },
    { "data": "LVA", "value": "Latvia" },
    { "data": "LBN", "value": "Lebanon" },
    { "data": "LSO", "value": "Lesotho" },
    { "data": "LBR", "value": "Liberia" },
    { "data": "LBY", "value": "Libyan Arab Jamahiriya" },
    { "data": "LIE", "value": "Liechtenstein" },
    { "data": "LTU", "value": "Lithuania" },
    { "data": "LUX", "value": "Luxembourg" },
    { "data": "MKD", "value": "Macedonia, The Fmr Yug Rp" },
    { "data": "MDG", "value": "Madagascar" },
    { "data": "MWI", "value": "Malawi" },
    { "data": "MYS", "value": "Malaysia" },
    { "data": "MDV", "value": "Maldives" },
    { "data": "MLI", "value": "Mali" },
    { "data": "MLT", "value": "Malta" },
    { "data": "MHL", "value": "Marshall Islands" },
    { "data": "MTQ", "value": "Martinique" },
    { "data": "MRT", "value": "Mauritania" },
    { "data": "MUS", "value": "Mauritius" },
    { "data": "MYT", "value": "Mayotte" },
    { "data": "MEX", "value": "Mexico" },
    { "data": "FSM", "value": "Micronesia, Fed States of" },
    { "data": "MDA", "value": "Moldova, Republic of" },
    { "data": "MNG", "value": "Mongolia" },
    { "data": "MSR", "value": "Montserrat" },
    { "data": "MAR", "value": "Morocco" },
    { "data": "MOZ", "value": "Mozambique" },
    { "data": "MMR", "value": "Myanmar" },
    { "data": "NAM", "value": "Namibia" },
    { "data": "NPL", "value": "Nepal" },
    { "data": "NLD", "value": "Netherlands" },
    { "data": "NCL", "value": "New Caledonia" },
    { "data": "NZL", "value": "New Zealand" },
    { "data": "NIC", "value": "Nicaragua" },
    { "data": "NER", "value": "Niger" },
    { "data": "NGA", "value": "Nigeria" },
    { "data": "NIU", "value": "Niue" },
    { "data": "PRK", "value": "Korea, Dem People's Rep" },
    { "data": "MNP", "value": "Northern Mariana Is" },
    { "data": "NOR", "value": "Norway" },
    { "data": "OMN", "value": "Oman" },
    { "data": "PAK", "value": "Pakistan" },
    { "data": "PLW", "value": "Palau" },
    { "data": "PSE", "value": "Palestine, Occupied Tr." },
    { "data": "PAN", "value": "Panama" },
    { "data": "PNG", "value": "Papua New Guinea" },
    { "data": "PRY", "value": "Paraguay" },
    { "data": "PER", "value": "Peru" },
    { "data": "PHL", "value": "Philippines" },
    { "data": "POL", "value": "Poland" },
    { "data": "PRT", "value": "Portugal" },
    { "data": "PRI", "value": "Puerto Rico" },
    { "data": "QAT", "value": "Qatar" },
    { "data": "COG", "value": "Congo, Republic of" },
    { "data": "REU", "value": "Réunion" },
    { "data": "ROU", "value": "Romania" },
    { "data": "RUS", "value": "Russian Federation" },
    { "data": "RWA", "value": "Rwanda" },
    { "data": "SHN", "value": "Saint Helena" },
    { "data": "KNA", "value": "Saint Kitts and Nevis" },
    { "data": "LCA", "value": "Saint Lucia" },
    { "data": "SPM", "value": "Saint Pierre & Miquelon" },
    { "data": "VCT", "value": "Saint Vincent/Grenadines" },
    { "data": "WSM", "value": "Samoa" },
    { "data": "SMR", "value": "San Marino" },
    { "data": "STP", "value": "Sao Tome and Principe" },
    { "data": "SAU", "value": "Saudi Arabia" },
    { "data": "SEN", "value": "Senegal" },
    { "data": "SRB", "value": "Serbia and Montenegro" },
    { "data": "SYC", "value": "Seychelles" },
    { "data": "SLE", "value": "Sierra Leone" },
    { "data": "SGP", "value": "Singapore" },
    { "data": "SVK", "value": "Slovakia" },
    { "data": "SVN", "value": "Slovenia" },
    { "data": "SLB", "value": "Solomon Islands" },
    { "data": "SOM", "value": "Somalia" },
    { "data": "ZAF", "value": "South Africa" },
    { "data": "KOR", "value": "Korea, Republic of" },
    { "data": "SSD", "value": "South Sudan" },
    { "data": "ESP", "value": "Spain" },
    { "data": "LKA", "value": "Sri Lanka" },
    { "data": "SDN", "value": "Sudan" },
    { "data": "SUR", "value": "Suriname" },
    { "data": "SWZ", "value": "Swaziland" },
    { "data": "SWE", "value": "Sweden" },
    { "data": "CHE", "value": "Switzerland" },
    { "data": "SYR", "value": "Syrian Arab Republic" },
    { "data": "TJK", "value": "Tajikistan" },
    { "data": "TZA", "value": "Tanzania, United Rep of" },
    { "data": "THA", "value": "Thailand" },
    { "data": "TLS", "value": "Timor-Leste" },
    { "data": "TGO", "value": "Togo" },
    { "data": "TON", "value": "Tonga" },
    { "data": "TTO", "value": "Trinidad and Tobago" },
    { "data": "TUN", "value": "Tunisia" },
    { "data": "TUR", "value": "Turkey" },
    { "data": "TKM", "value": "Turkmenistan" },
    { "data": "TCA", "value": "Turks and Caicos Is" },
    { "data": "TUV", "value": "Tuvalu" },
    { "data": "UGA", "value": "Uganda" },
    { "data": "UKR", "value": "Ukraine" },
    { "data": "ARE", "value": "United Arab Emirates" },
    { "data": "GBR", "value": "United Kingdom" },
    { "data": "USA", "value": "United States of America" },
    { "data": "URY", "value": "Uruguay" },
    { "data": "UZB", "value": "Uzbekistan" },
    { "data": "VUT", "value": "Vanuatu" },
    { "data": "VEN", "value": "Venezuela,Bolivar Rep of" },
    { "data": "VNM", "value": "Viet Nam" },
    { "data": "VIR", "value": "US Virgin Islands" },
    { "data": "WLF", "value": "Wallis and Futuna Is" },
    { "data": "ESH", "value": "Western Sahara" },
    { "data": "YEM", "value": "Yemen" },
    { "data": "ZMB", "value": "Zambia" },
    { "data": "ZWE", "value": "Zimbabwe" }
]

module.exports = countries
