/**
 * @author Mino Togna
 */

var countries = [
    {
        "value":"Afghanistan",
        "data":"AF"
    },
    {
        "value":"Albania",
        "data":"AL"
    },
    {
        "value":"Algeria",
        "data":"DZ"
    },
    {
        "value":"Andorra",
        "data":"AD"
    },
    {
        "value":"Angola",
        "data":"AO"
    },
    {
        "value":"Antigua and Barbuda",
        "data":"AG"
    },
    {
        "value":"Argentina",
        "data":"AR"
    },
    {
        "value":"Armenia",
        "data":"AM"
    },
    {
        "value":"Australia",
        "data":"AU"
    },
    {
        "value":"Austria",
        "data":"AT"
    },
    {
        "value":"Azerbaijan",
        "data":"AZ"
    },
    {
        "value":"Bahamas, The",
        "data":"BS"
    },
    {
        "value":"Bahrain",
        "data":"BH"
    },
    {
        "value":"Bangladesh",
        "data":"BD"
    },
    {
        "value":"Barbados",
        "data":"BB"
    },
    {
        "value":"Belarus",
        "data":"BY"
    },
    {
        "value":"Belgium",
        "data":"BE"
    },
    {
        "value":"Belize",
        "data":"BZ"
    },
    {
        "value":"Benin",
        "data":"BJ"
    },
    {
        "value":"Bhutan",
        "data":"BT"
    },
    {
        "value":"Bolivia",
        "data":"BO"
    },
    {
        "value":"Bosnia and Herzegovina",
        "data":"BA"
    },
    {
        "value":"Botswana",
        "data":"BW"
    },
    {
        "value":"Brazil",
        "data":"BR"
    },
    {
        "value":"Brunei",
        "data":"BN"
    },
    {
        "value":"Bulgaria",
        "data":"BG"
    },
    {
        "value":"Burkina Faso",
        "data":"BF"
    },
    {
        "value":"Burundi",
        "data":"BI"
    },
    {
        "value":"Cambodia",
        "data":"KH"
    },
    {
        "value":"Cameroon",
        "data":"CM"
    },
    {
        "value":"Canada",
        "data":"CA"
    },
    {
        "value":"Cape Verde",
        "data":"CV"
    },
    {
        "value":"Central African Republic",
        "data":"CF"
    },
    {
        "value":"Chad",
        "data":"TD"
    },
    {
        "value":"Chile",
        "data":"CL"
    },
    {
        "value":"China, People's Republic of",
        "data":"CN"
    },
    {
        "value":"Colombia",
        "data":"CO"
    },
    {
        "value":"Comoros",
        "data":"KM"
    },
    {
        "value":"Congo, (Congo �� Kinshasa)",
        "data":"CD"
    },
    {
        "value":"Congo, (Congo �� Brazzaville)",
        "data":"CG"
    },
    {
        "value":"Costa Rica",
        "data":"CR"
    },
    {
        "value":"Cote d'Ivoire (Ivory Coast)",
        "data":"CI"
    },
    {
        "value":"Croatia",
        "data":"HR"
    },
    {
        "value":"Cuba",
        "data":"CU"
    },
    {
        "value":"Cyprus",
        "data":"CY"
    },
    {
        "value":"Czech Republic",
        "data":"CZ"
    },
    {
        "value":"Denmark",
        "data":"DK"
    },
    {
        "value":"Djibouti",
        "data":"DJ"
    },
    {
        "value":"Dominica",
        "data":"DM"
    },
    {
        "value":"Dominican Republic",
        "data":"DO"
    },
    {
        "value":"Ecuador",
        "data":"EC"
    },
    {
        "value":"Egypt",
        "data":"EG"
    },
    {
        "value":"El Salvador",
        "data":"SV"
    },
    {
        "value":"Equatorial Guinea",
        "data":"GQ"
    },
    {
        "value":"Eritrea",
        "data":"ER"
    },
    {
        "value":"Estonia",
        "data":"EE"
    },
    {
        "value":"Ethiopia",
        "data":"ET"
    },
    {
        "value":"Fiji",
        "data":"FJ"
    },
    {
        "value":"Finland",
        "data":"FI"
    },
    {
        "value":"France",
        "data":"FR"
    },
    {
        "value":"Gabon",
        "data":"GA"
    },
    {
        "value":"Gambia, The",
        "data":"GM"
    },
    {
        "value":"Georgia",
        "data":"GE"
    },
    {
        "value":"Germany",
        "data":"DE"
    },
    {
        "value":"Ghana",
        "data":"GH"
    },
    {
        "value":"Greece",
        "data":"GR"
    },
    {
        "value":"Grenada",
        "data":"GD"
    },
    {
        "value":"Guatemala",
        "data":"GT"
    },
    {
        "value":"Guinea",
        "data":"GN"
    },
    {
        "value":"Guinea-Bissau",
        "data":"GW"
    },
    {
        "value":"Guyana",
        "data":"GY"
    },
    {
        "value":"Haiti",
        "data":"HT"
    },
    {
        "value":"Honduras",
        "data":"HN"
    },
    {
        "value":"Hungary",
        "data":"HU"
    },
    {
        "value":"Iceland",
        "data":"IS"
    },
    {
        "value":"India",
        "data":"IN"
    },
    {
        "value":"Indonesia",
        "data":"ID"
    },
    {
        "value":"Iran",
        "data":"IR"
    },
    {
        "value":"Iraq",
        "data":"IQ"
    },
    {
        "value":"Ireland",
        "data":"IE"
    },
    {
        "value":"Israel",
        "data":"IL"
    },
    {
        "value":"Italy",
        "data":"IT"
    },
    {
        "value":"Jamaica",
        "data":"JM"
    },
    {
        "value":"Japan",
        "data":"JP"
    },
    {
        "value":"Jordan",
        "data":"JO"
    },
    {
        "value":"Kazakhstan",
        "data":"KZ"
    },
    {
        "value":"Kenya",
        "data":"KE"
    },
    {
        "value":"Kiribati",
        "data":"KI"
    },
    {
        "value":"Korea, North",
        "data":"KP"
    },
    {
        "value":"Korea, South",
        "data":"KR"
    },
    {
        "value":"Kuwait",
        "data":"KW"
    },
    {
        "value":"Kyrgyzstan",
        "data":"KG"
    },
    {
        "value":"Laos",
        "data":"LA"
    },
    {
        "value":"Latvia",
        "data":"LV"
    },
    {
        "value":"Lebanon",
        "data":"LB"
    },
    {
        "value":"Lesotho",
        "data":"LS"
    },
    {
        "value":"Liberia",
        "data":"LR"
    },
    {
        "value":"Libya",
        "data":"LY"
    },
    {
        "value":"Liechtenstein",
        "data":"LI"
    },
    {
        "value":"Lithuania",
        "data":"LT"
    },
    {
        "value":"Luxembourg",
        "data":"LU"
    },
    {
        "value":"Macedonia",
        "data":"MK"
    },
    {
        "value":"Madagascar",
        "data":"MG"
    },
    {
        "value":"Malawi",
        "data":"MW"
    },
    {
        "value":"Malaysia",
        "data":"MY"
    },
    {
        "value":"Maldives",
        "data":"MV"
    },
    {
        "value":"Mali",
        "data":"ML"
    },
    {
        "value":"Malta",
        "data":"MT"
    },
    {
        "value":"Marshall Islands",
        "data":"MH"
    },
    {
        "value":"Mauritania",
        "data":"MR"
    },
    {
        "value":"Mauritius",
        "data":"MU"
    },
    {
        "value":"Mexico",
        "data":"MX"
    },
    {
        "value":"Micronesia",
        "data":"FM"
    },
    {
        "value":"Moldova",
        "data":"MD"
    },
    {
        "value":"Monaco",
        "data":"MC"
    },
    {
        "value":"Mongolia",
        "data":"MN"
    },
    {
        "value":"Montenegro",
        "data":"ME"
    },
    {
        "value":"Morocco",
        "data":"MA"
    },
    {
        "value":"Mozambique",
        "data":"MZ"
    },
    {
        "value":"Myanmar (Burma)",
        "data":"MM"
    },
    {
        "value":"Namibia",
        "data":"NA"
    },
    {
        "value":"Nauru",
        "data":"NR"
    },
    {
        "value":"Nepal",
        "data":"NP"
    },
    {
        "value":"Netherlands",
        "data":"NL"
    },
    {
        "value":"New Zealand",
        "data":"NZ"
    },
    {
        "value":"Nicaragua",
        "data":"NI"
    },
    {
        "value":"Niger",
        "data":"NE"
    },
    {
        "value":"Nigeria",
        "data":"NG"
    },
    {
        "value":"Norway",
        "data":"NO"
    },
    {
        "value":"Oman",
        "data":"OM"
    },
    {
        "value":"Pakistan",
        "data":"PK"
    },
    {
        "value":"Palau",
        "data":"PW"
    },
    {
        "value":"Panama",
        "data":"PA"
    },
    {
        "value":"Papua New Guinea",
        "data":"PG"
    },
    {
        "value":"Paraguay",
        "data":"PY"
    },
    {
        "value":"Peru",
        "data":"PE"
    },
    {
        "value":"Philippines",
        "data":"PH"
    },
    {
        "value":"Poland",
        "data":"PL"
    },
    {
        "value":"Portugal",
        "data":"PT"
    },
    {
        "value":"Qatar",
        "data":"QA"
    },
    {
        "value":"Romania",
        "data":"RO"
    },
    {
        "value":"Russia",
        "data":"RU"
    },
    {
        "value":"Rwanda",
        "data":"RW"
    },
    {
        "value":"Saint Kitts and Nevis",
        "data":"KN"
    },
    {
        "value":"Saint Lucia",
        "data":"LC"
    },
    {
        "value":"Saint Vincent and the Grenadines",
        "data":"VC"
    },
    {
        "value":"Samoa",
        "data":"WS"
    },
    {
        "value":"San Marino",
        "data":"SM"
    },
    {
        "value":"Sao Tome and Principe",
        "data":"ST"
    },
    {
        "value":"Saudi Arabia",
        "data":"SA"
    },
    {
        "value":"Senegal",
        "data":"SN"
    },
    {
        "value":"Serbia",
        "data":"RS"
    },
    {
        "value":"Seychelles",
        "data":"SC"
    },
    {
        "value":"Sierra Leone",
        "data":"SL"
    },
    {
        "value":"Singapore",
        "data":"SG"
    },
    {
        "value":"Slovakia",
        "data":"SK"
    },
    {
        "value":"Slovenia",
        "data":"SI"
    },
    {
        "value":"Solomon Islands",
        "data":"SB"
    },
    {
        "value":"Somalia",
        "data":"SO"
    },
    {
        "value":"South Africa",
        "data":"ZA"
    },
    {
        "value":"Spain",
        "data":"ES"
    },
    {
        "value":"Sri Lanka",
        "data":"LK"
    },
    {
        "value":"Sudan",
        "data":"SD"
    },
    {
        "value":"Suriname",
        "data":"SR"
    },
    {
        "value":"Swaziland",
        "data":"SZ"
    },
    {
        "value":"Sweden",
        "data":"SE"
    },
    {
        "value":"Switzerland",
        "data":"CH"
    },
    {
        "value":"Syria",
        "data":"SY"
    },
    {
        "value":"Tajikistan",
        "data":"TJ"
    },
    {
        "value":"Tanzania",
        "data":"TZ"
    },
    {
        "value":"Thailand",
        "data":"TH"
    },
    {
        "value":"Timor-Leste (East Timor)",
        "data":"TL"
    },
    {
        "value":"Togo",
        "data":"TG"
    },
    {
        "value":"Tonga",
        "data":"TO"
    },
    {
        "value":"Trinidad and Tobago",
        "data":"TT"
    },
    {
        "value":"Tunisia",
        "data":"TN"
    },
    {
        "value":"Turkey",
        "data":"TR"
    },
    {
        "value":"Turkmenistan",
        "data":"TM"
    },
    {
        "value":"Tuvalu",
        "data":"TV"
    },
    {
        "value":"Uganda",
        "data":"UG"
    },
    {
        "value":"Ukraine",
        "data":"UA"
    },
    {
        "value":"United Arab Emirates",
        "data":"AE"
    },
    {
        "value":"United Kingdom",
        "data":"GB"
    },
    {
        "value":"United States",
        "data":"US"
    },
    {
        "value":"Uruguay",
        "data":"UY"
    },
    {
        "value":"Uzbekistan",
        "data":"UZ"
    },
    {
        "value":"Vanuatu",
        "data":"VU"
    },
    {
        "value":"Vatican City",
        "data":"VA"
    },
    {
        "value":"Venezuela",
        "data":"VE"
    },
    {
        "value":"Vietnam",
        "data":"VN"
    },
    {
        "value":"Yemen",
        "data":"YE"
    },
    {
        "value":"Zambia",
        "data":"ZM"
    },
    {
        "value":"Zimbabwe",
        "data":"ZW"
    },
    {
        "value":"Abkhazia",
        "data":"GE"
    },
    {
        "value":"China, Republic of (Taiwan)",
        "data":"TW"
    },
    {
        "value":"Nagorno-Karabakh",
        "data":"AZ"
    },
    {
        "value":"Northern Cyprus",
        "data":"CY"
    },
    {
        "value":"Pridnestrovie (Transnistria)",
        "data":"MD"
    },
    {
        "value":"Somaliland",
        "data":"SO"
    },
    {
        "value":"South Ossetia",
        "data":"GE"
    },
    {
        "value":"Ashmore and Cartier Islands",
        "data":"AU"
    },
    {
        "value":"Christmas Island",
        "data":"CX"
    },
    {
        "value":"Cocos (Keeling) Islands",
        "data":"CC"
    },
    {
        "value":"Coral Sea Islands",
        "data":"AU"
    },
    {
        "value":"Heard Island and McDonald Islands",
        "data":"HM"
    },
    {
        "value":"Norfolk Island",
        "data":"NF"
    },
    {
        "value":"New Caledonia",
        "data":"NC"
    },
    {
        "value":"French Polynesia",
        "data":"PF"
    },
    {
        "value":"Mayotte",
        "data":"YT"
    },
    {
        "value":"Saint Barthelemy",
        "data":"GP"
    },
    {
        "value":"Saint Martin",
        "data":"GP"
    },
    {
        "value":"Saint Pierre and Miquelon",
        "data":"PM"
    },
    {
        "value":"Wallis and Futuna",
        "data":"WF"
    },
    {
        "value":"French Southern and Antarctic Lands",
        "data":"TF"
    },
    {
        "value":"Clipperton Island",
        "data":"PF"
    },
    {
        "value":"Bouvet Island",
        "data":"BV"
    },
    {
        "value":"Cook Islands",
        "data":"CK"
    },
    {
        "value":"Niue",
        "data":"NU"
    },
    {
        "value":"Tokelau",
        "data":"TK"
    },
    {
        "value":"Guernsey",
        "data":"GG"
    },
    {
        "value":"Isle of Man",
        "data":"IM"
    },
    {
        "value":"Jersey",
        "data":"JE"
    },
    {
        "value":"Anguilla",
        "data":"AI"
    },
    {
        "value":"Bermuda",
        "data":"BM"
    },
    {
        "value":"British Indian Ocean Territory",
        "data":"IO"
    },
    {
        "value":"British Sovereign Base Areas",
        "data":""
    },
    {
        "value":"British Virgin Islands",
        "data":"VG"
    },
    {
        "value":"Cayman Islands",
        "data":"KY"
    },
    {
        "value":"Falkland Islands (Islas Malvinas)",
        "data":"FK"
    },
    {
        "value":"Gibraltar",
        "data":"GI"
    },
    {
        "value":"Montserrat",
        "data":"MS"
    },
    {
        "value":"Pitcairn Islands",
        "data":"PN"
    },
    {
        "value":"Saint Helena",
        "data":"SH"
    },
    {
        "value":"South Georgia & South Sandwich Islands",
        "data":"GS"
    },
    {
        "value":"Turks and Caicos Islands",
        "data":"TC"
    },
    {
        "value":"Northern Mariana Islands",
        "data":"MP"
    },
    {
        "value":"Puerto Rico",
        "data":"PR"
    },
    {
        "value":"American Samoa",
        "data":"AS"
    },
    {
        "value":"Baker Island",
        "data":"UM"
    },
    {
        "value":"Guam",
        "data":"GU"
    },
    {
        "value":"Howland Island",
        "data":"UM"
    },
    {
        "value":"Jarvis Island",
        "data":"UM"
    },
    {
        "value":"Johnston Atoll",
        "data":"UM"
    },
    {
        "value":"Kingman Reef",
        "data":"UM"
    },
    {
        "value":"Midway Islands",
        "data":"UM"
    },
    {
        "value":"Navassa Island",
        "data":"UM"
    },
    {
        "value":"Palmyra Atoll",
        "data":"UM"
    },
    {
        "value":"U.S. Virgin Islands",
        "data":"VI"
    },
    {
        "value":"Wake Island",
        "data":"UM"
    },
    {
        "value":"Hong Kong",
        "data":"HK"
    },
    {
        "value":"Macau",
        "data":"MO"
    },
    {
        "value":"Faroe Islands",
        "data":"FO"
    },
    {
        "value":"Greenland",
        "data":"GL"
    },
    {
        "value":"French Guiana",
        "data":"GF"
    },
    {
        "value":"Guadeloupe",
        "data":"GP"
    },
    {
        "value":"Martinique",
        "data":"MQ"
    },
    {
        "value":"Reunion",
        "data":"RE"
    },
    {
        "value":"Aland",
        "data":"AX"
    },
    {
        "value":"Aruba",
        "data":"AW"
    },
    {
        "value":"Netherlands Antilles",
        "data":"AN"
    },
    {
        "value":"Svalbard",
        "data":"SJ"
    },
    {
        "value":"Ascension",
        "data":"AC"
    },
    {
        "value":"Tristan da Cunha",
        "data":"TA"
    },
    {
        "value":"Australian Antarctic Territory",
        "data":"AQ"
    },
    {
        "value":"Ross Dependency",
        "data":"AQ"
    },
    {
        "value":"Peter I Island",
        "data":"AQ"
    },
    {
        "value":"Queen Maud Land",
        "data":"AQ"
    },
    {
        "value":"British Antarctic Territory",
        "data":"AQ"
    }
]

module.exports = countries
