#!/usr/bin/env bash

uri=$(curl -s "http://sepal:1025/data/sandbox/$USER" | jq -r '.uri')
sandboxId=$(curl -s "http://sepal:1025/data/sandbox/$USER" | jq -r '.sandboxId')
/alive.sh $sandboxId > /dev/null 2>&1 &
ssh -YC -i /home/$USER/.ssh/id_rsa -l $USER $uri ${SSH_ORIGINAL_COMMAND:-}

