export const MODULE_UP = 'moduleUp' // {module}
export const MODULE_DOWN = 'moduleDown' // {module}
export const USER_UP = 'userUp' // {user}
export const USER_DOWN = 'userDown' // {user}
export const USER_UPDATED = 'userUpdated' // {user}
export const CLIENT_UP = 'clientUp' // {username, clientId}
export const CLIENT_DOWN = 'clientDown' // {username, clientId}
export const CLIENT_VERSION_MISMATCH = 'clientVersionMismatch' // {username, clientId}
export const LOGIN_SESSION_INVALIDATED = 'loginSessionInvalidated' // {username, sessionId, reason: 'logout' | 'replaced' | 'invalidated' | 'locked'}
export const SUBSCRIPTION_UP = 'subscriptionUp' // {module, username, clientId, subscriptionId}
export const SUBSCRIPTION_DOWN = 'subscriptionDown' // {module, username, clientId, subscriptionId}
export const GOOGLE_ACCESS_TOKEN_ADDED = 'googleAccessTokenAdded' // {user}
export const GOOGLE_ACCESS_TOKEN_UPDATED = 'googleAccessTokenUpdated' // {user}
export const GOOGLE_ACCESS_TOKEN_REMOVED = 'googleAccessTokenRemoved' // {user}
export const WORKER_SESSION_CLOSED = 'workerSessionClosed' // {username, sessionId}
export const WORKER_SESSION_APP_DISSOCIATED = 'workerSessionAppDissociated' // {username, clientId, appPath, sessionId}
export const WORKER_SESSION_EXPIRY_NOTIFIED = 'workerSessionExpiryNotified' // {username, sessionId, apps, terminals, ordinal, instanceName}
export const WORKER_SESSION_EXPIRY_CLOSED = 'workerSessionExpiryClosed' // {username, sessionId, apps, terminals, ordinal, instanceName}
