# -*- mode: ruby -*-
# vi: set ft=ruby :

project_dir = '../../..'

Vagrant.configure(2) do |config|
  config.vm.network 'private_network', ip: "#{ENV['VAGRANT_IP']}"
  config.vm.box = 'ubuntu/trusty64'
  config.vm.synced_folder project_dir, '/opt/sepal/'

  config.vm.provider 'virtualbox' do |v|
    v.memory = 3072
    v.name = 'operations'
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'deploy.yml'
    #ansible.verbose = 'vvvv'
    ansible.extra_vars = {
        ansible_ssh_user: 'vagrant',
        secret_vars_file: "#{ENV['CONFIG_HOME']}/secret.yml",
        docker_repository_host: 'localhost',
        config_home:"#{ENV['CONFIG_HOME']}",
        version: '1'
    }
  end
end
