import datasets$ from '#gee/jobs/datasets/datasets'
import aoiBounds$ from '#gee/jobs/ee/aoi/bounds'
import aoiGeometry$ from '#gee/jobs/ee/aoi/geometry'
import createFolder$ from '#gee/jobs/ee/asset/createFolder'
import deleteAsset$ from '#gee/jobs/ee/asset/delete'
import listAssets$ from '#gee/jobs/ee/asset/list'
import assetMetadata$ from '#gee/jobs/ee/asset/metadata'
import renameAsset$ from '#gee/jobs/ee/asset/rename'
import loadCCDCSegments$ from '#gee/jobs/ee/ccdc/loadSegments'
import check$ from '#gee/jobs/ee/check'
import nextReferenceDataPoints$ from '#gee/jobs/ee/classification/nextReferenceDataPoints'
import imageBands$ from '#gee/jobs/ee/image/bands'
import imageBounds$ from '#gee/jobs/ee/image/bounds'
import distinctBandValues$ from '#gee/jobs/ee/image/distinctBandValues'
import imageJson$ from '#gee/jobs/ee/image/eeJson'
import imageGeometry$ from '#gee/jobs/ee/image/geometry'
import imageHistogram$ from '#gee/jobs/ee/image/histogram'
import landsatProductId$ from '#gee/jobs/ee/image/landsatProductId'
import preview$ from '#gee/jobs/ee/image/preview'
import sampleImage$ from '#gee/jobs/ee/image/sample'
import sceneAreas$ from '#gee/jobs/ee/image/sceneAreas'
import loadLandTrendrSegments$ from '#gee/jobs/ee/landTrendr/loadSegments'
import projects$ from '#gee/jobs/ee/projects'
import areaPerStratum$ from '#gee/jobs/ee/samplingDesign/areaPerStratum'
import probabilityPerStratum$ from '#gee/jobs/ee/samplingDesign/probabilityPerStratum'
import tableColumns$ from '#gee/jobs/ee/table/columns'
import tableColumnValues$ from '#gee/jobs/ee/table/columnValues'
import tableMap$ from '#gee/jobs/ee/table/map'
import tableQuery$ from '#gee/jobs/ee/table/query'
import tableRows$ from '#gee/jobs/ee/table/rows'
import listCompletedTasks$ from '#gee/jobs/ee/task/listCompleted'
import loadTimeSeriesbservations$ from '#gee/jobs/ee/timeSeries/loadObservations'
import taskDownloadCleanup$ from '#gee/jobs/task/downloadCleanup'
import taskDownloadFiles$ from '#gee/jobs/task/downloadFiles'
import taskExportCcdcToAsset$ from '#gee/jobs/task/exportCcdcToAsset'
import taskExportImageToAsset$ from '#gee/jobs/task/exportImageToAsset'
import taskExportImageToDrive$ from '#gee/jobs/task/exportImageToDrive'
import taskOperationCancel$ from '#gee/jobs/task/operationCancel'
import taskOperationStatus$ from '#gee/jobs/task/operationStatus'
import taskShareAsset$ from '#gee/jobs/task/shareAsset'
import {stream} from '#sepal/httpServer'

export default router =>
    router
        .post('/sceneareas', stream(ctx => sceneAreas$(ctx)))
        .post('/preview', stream(ctx => preview$(ctx)))
        .post('/bands', stream(ctx => imageBands$(ctx)))
        .get('/image/json', stream(ctx => {
            ctx.type = 'application/json'
            return imageJson$(ctx)
        }))
        .post('/image/histogram', stream(ctx => imageHistogram$(ctx)))
        .post('/image/distinctBandValues', stream(ctx => distinctBandValues$(ctx)))
        .post('/image/sample', stream(ctx => sampleImage$(ctx)))
        .post('/assetMetadata', stream(ctx => assetMetadata$(ctx)))
        .get('/projects', stream(ctx => projects$(ctx)))
        .get('/asset/descendants', stream(ctx => listAssets$(ctx)))
        .post('/asset/createFolder', stream(ctx => createFolder$(ctx)))
        .post('/asset/rename', stream(ctx => renameAsset$(ctx)))
        .delete('/asset/delete', stream(ctx => deleteAsset$(ctx)))
        .get('/task/listCompleted', stream(ctx => listCompletedTasks$(ctx)))
        .post('/recipe/geometry', stream(ctx => imageGeometry$(ctx)))
        .post('/recipe/bounds', stream(ctx => imageBounds$(ctx)))
        .post('/aoi/bounds', stream(ctx => aoiBounds$(ctx)))
        .post('/aoi/geometry', stream(ctx => aoiGeometry$(ctx)))
        .post('/ccdc/loadSegments', stream(ctx => loadCCDCSegments$(ctx)))
        .post('/landTrendr/loadSegments', stream(ctx => loadLandTrendrSegments$(ctx)))
        .post('/timeSeries/loadObservations', stream(ctx => loadTimeSeriesbservations$(ctx)))
        .post('/nextReferenceDataPoints', stream(ctx => nextReferenceDataPoints$(ctx)))
        .get('/table/rows', stream(ctx => tableRows$(ctx)))
        .get('/table/columns', stream(ctx => tableColumns$(ctx)))
        .get('/table/columnValues', stream(ctx => tableColumnValues$(ctx)))
        .post('/table/query', stream(ctx => tableQuery$(ctx)))
        .get('/table/map', stream(ctx => tableMap$(ctx)))
        .post('/samplingDesign/areaPerStratum', stream(ctx => areaPerStratum$(ctx)))
        .post('/samplingDesign/probabilityPerStratum', stream(ctx => probabilityPerStratum$(ctx)))
        .get('/datasets', stream(ctx => datasets$(ctx)))
        .get('/landsatProductId', stream(ctx => landsatProductId$(ctx)))
        .post('/task/operation/status', stream(ctx => taskOperationStatus$(ctx)))
        .post('/task/operation/cancel', stream(ctx => taskOperationCancel$(ctx)))
        .post('/task/export/ccdc/asset', stream(ctx => taskExportCcdcToAsset$(ctx)))
        .post('/task/export/image/asset', stream(ctx => taskExportImageToAsset$(ctx)))
        .post('/task/export/image/drive', stream(ctx => taskExportImageToDrive$(ctx)))
        .post('/task/download/files', stream(ctx => taskDownloadFiles$(ctx)))
        .post('/task/download/cleanup', stream(ctx => taskDownloadCleanup$(ctx)))
        .post('/task/asset/share', stream(ctx => taskShareAsset$(ctx)))
        .get('/healthcheck', stream(ctx => check$(ctx)))
