import {stream} from '#sepal/httpServer'
import sceneAreas$ from '#gee/jobs/ee/image/sceneAreas'
import preview$ from '#gee/jobs/ee/image/preview'
import loadCCDCSegments$ from '#gee/jobs/ee/ccdc/loadSegments'
import loadTimeSeriesbservations$ from '#gee/jobs/ee/timeSeries/loadObservations'
import nextReferenceDataPoints$ from '#gee/jobs/ee/classification/nextReferenceDataPoints'
import imageBands$ from '#gee/jobs/ee/image/bands'
import imageHistogram$ from '#gee/jobs/ee/image/histogram'
import imageJson$ from '#gee/jobs/ee/image/eeJson'
import distinctBandValues$ from '#gee/jobs/ee/image/distinctBandValues'
import assetMetadata$ from '#gee/jobs/ee/asset/metadata'
import projects$ from '#gee/jobs/ee/projects'
import listAssets$ from '#gee/jobs/ee/asset/list'
import createFolder$ from '#gee/jobs/ee/asset/createFolder'
import renameAsset$ from '#gee/jobs/ee/asset/rename'
import deleteAsset$ from '#gee/jobs/ee/asset/delete'
import listCompletedTasks$ from '#gee/jobs/ee/task/listCompleted'
import imageBounds$ from '#gee/jobs/ee/image/bounds'
import imageGeometry$ from '#gee/jobs/ee/image/geometry'
import sampleImage$ from '#gee/jobs/ee/image/sample'
import aoiBounds$ from '#gee/jobs/ee/aoi/bounds'
import tableColumns$ from '#gee/jobs/ee/table/columns'
import tableColumnValues$ from '#gee/jobs/ee/table/columnValues'
import tableRows$ from '#gee/jobs/ee/table/rows'
import tableQuery$ from '#gee/jobs/ee/table/query'
import tableMap$ from '#gee/jobs/ee/table/map'
import datasets$ from '#gee/jobs/datasets/datasets'
import landsatProductId$ from '#gee/jobs/ee/image/landsatProductId'
import check$ from '#gee/jobs/ee/check'

export default router =>
    router
        .post('/sceneareas', stream(ctx => sceneAreas$(ctx)))
        .post('/preview', stream(ctx => preview$(ctx)))
        .post('/bands', stream(ctx => imageBands$(ctx)))
        .get('/image/json', stream(ctx => {
            ctx.type = 'application/json'
            return imageJson$(ctx)
        }))
        .post('/image/histogram', stream(ctx => imageHistogram$(ctx)))
        .post('/image/distinctBandValues', stream(ctx => distinctBandValues$(ctx)))
        .post('/image/sample', stream(ctx => sampleImage$(ctx)))
        .post('/assetMetadata', stream(ctx => assetMetadata$(ctx)))
        .get('/projects', stream(ctx => projects$(ctx)))
        .get('/asset/descendants', stream(ctx => listAssets$(ctx)))
        .post('/asset/createFolder', stream(ctx => createFolder$(ctx)))
        .post('/asset/rename', stream(ctx => renameAsset$(ctx)))
        .delete('/asset/delete', stream(ctx => deleteAsset$(ctx)))
        .get('/task/listCompleted', stream(ctx => listCompletedTasks$(ctx)))
        .post('/recipe/geometry', stream(ctx => imageGeometry$(ctx)))
        .post('/recipe/bounds', stream(ctx => imageBounds$(ctx)))
        .post('/aoi/bounds', stream(ctx => aoiBounds$(ctx)))
        .post('/ccdc/loadSegments', stream(ctx => loadCCDCSegments$(ctx)))
        .post('/timeSeries/loadObservations', stream(ctx => loadTimeSeriesbservations$(ctx)))
        .post('/nextReferenceDataPoints', stream(ctx => nextReferenceDataPoints$(ctx)))
        .get('/table/rows', stream(ctx => tableRows$(ctx)))
        .get('/table/columns', stream(ctx => tableColumns$(ctx)))
        .get('/table/columnValues', stream(ctx => tableColumnValues$(ctx)))
        .post('/table/query', stream(ctx => tableQuery$(ctx)))
        .get('/table/map', stream(ctx => tableMap$(ctx)))
        .get('/datasets', stream(ctx => datasets$(ctx)))
        .get('/landsatProductId', stream(ctx => landsatProductId$(ctx)))
        .get('/healthcheck', stream(ctx => check$(ctx)))
