#!/bin/bash
set -e
echo
echo "*****************************************"
echo "*** Installing R packages ***"
echo "*****************************************"
R -e "install.packages('devtools', dependencies=TRUE, repos='http://r-proxy:8180/')"
R -e "install.packages(c(\
        'abind',\
        'askpass',\
        'assertthat',\
        'backports',\
        'base64enc',\
        'BH',\
        'BiodiversityR',\
        'bit',\
        'bit64',\
        'blob',\
        'brew',\
        'broom',\
        'callr',\
        'car',\
        'caret',\
        'cellranger',\
        'chron',\
        'classInt',\
        'cli',\
        'clipr',\
        'collapsibleTree',\
        'colorspace',\
        'colourpicker',\
        'corrplot',\
        'countrycode',\
        'crayon',\
        'curl',\
        'data.table',\
        'DBI',\
        'DBItest',\
        'dbplyr',\
        'desc',\
        'devtools',\
        'DiagrammeR',\
        'dichromat',\
        'digest',\
        'dismo',\
        'doMC',\
        'doParallel',\
        'downloader',\
        'dplyr',\
        'DT',\
        'e1071',\
        'ellipsis',\
        'evaluate',\
        'evir',\
        'expss',\
        'fansi',\
        'fasterize',\
        'feather',\
        'filehash',\
        'forcats',\
        'foreach',\
        'forecast',\
        'foreign',\
        'formatR',\
        'formattable',\
        'Formula',\
        'fs',\
        'future',\
        'generics',\
        'geoR',\
        'geosphere',\
        'ggalluvial',\
        'ggExtra',\
        'ggfortify',\
        'ggmap',\
        'ggplot2',\
        'ggrepel',\
        'ggthemes',\
        'ggthemr',\
        'GISTools',\
        'glmnet',\
        'globals',\
        'glue',\
        'googleVis',\
        'gpclib',\
        'grid',\
        'gridExtra',\
        'gsubfn',\
        'gtable',\
        'haven',\
        'hexbin',\
        'highr',\
        'Hmisc',\
        'hms',\
        'htmltools',\
        'htmlwidgets',\
        'httpuv',\
        'httr',\
        'igraph',\
        'influenceR',\
        'iterators',\
        'jpeg',\
        'jsonlite',\
        'kableExtra',\
        'keras',\
        'knitr',\
        'labeling',\
        'later',\
        'lattice',\
        'latticeExtra',\
        'lazyeval',\
        'leafem',\
        'leaflet',\
        'leaflet.extras',\
        'lifecycle',\
        'listenv',\
        'littler',\
        'lme4',\
        'lmfor',\
        'lubridate',\
        'magick',\
        'magrittr',\
        'manipulate',\
        'mapproj',\
        'maps',\
        'maptools',\
        'markdown',\
        'MASS',\
        'memoise',\
        'mgcv',\
        'mime',\
        'miniUI',\
        'missForest',\
        'mockery',\
        'mockr',\
        'modelr',\
        'moments',\
        'multcomp',\
        'multicore',\
        'munsell',\
        'ncdf4',\
        'networkD3',\
        'nlme',\
        'nlstools',\
        'openssl',\
        'outliers',\
        'pacman',\
        'parallel',\
        'party',\
        'permutate',\
        'pillar',\
        'pkgconfig',\
        'pkgKitten',\
        'plotly',\
        'plyr',\
        'png',\
        'PracTools',\
        'praise',\
        'prettycode',\
        'prettyunits',\
        'processx',\
        'progress',\
        'promises',\
        'proto',\
        'ps',\
        'purrr',\
        'quantmod',\
        'R6',\
        'random',\
        'randomForest',\
        'raster',\
        'rasterVis',\
        'rclipboard',\
        'RColorBrewer',\
        'Rcpp',\
        'RcppArmadillo',\
        'RcppEigen',\
        'RCurl',\
        'readr',\
        'readxl',\
        'rematch',\
        'rematch2',\
        'rentrez',\
        'reprex',\
        'reshape',\
        'reshape2',\
        'reticulate',\
        'rgbif',\
        'rgeos',\
        'rgexf',\
        'RgoogleMaps',\
        'rhandsontable',\
        'rlang',\
        'rmarkdown',\
        'Rmpi',\
        'Rook',\
        'rpart',\
        'rpart.plot',\
        'RPostgreSQL',\
        'rprojroot',\
        'rsconnect',\
        'RSQLite',\
        'rstudioapi',\
        'rticles',\
        'RUnit',\
        'rvest',\
        'Rweka',\
        'rworldmap',\
        'samplingbook',\
        'scales',\
        'selectr',\
        'shiny',\
        'shinyBS',\
        'shinycssloaders',\
        'shinydashboard',\
        'shinyFiles',\
        'shinyjs',\
        'skimr',\
        'snow',\
        'sourcetools',\
        'sp',\
        'spatial',\
        'splines',\
        'sqldf',\
        'stats',\
        'stats4',\
        'stringi',\
        'stringr',\
        'styler',\
        'summarytools',\
        'survival',\
        'sys',\
        'taxize',\
        'Taxonstand',\
        'testit',\
        'testthat',\
        'textclean',\
        'tibble',\
        'tictoc',\
        'tidyr',\
        'tidyselect',\
        'tidyverse',\
        'tikzDevice',\
        'tint',\
        'tinytex',\
        'tools',\
        'treemap',\
        'tufte',\
        'units',\
        'UpSetR',\
        'urltools',\
        'utf8',\
        'utils',\
        'vcd',\
        'vctrs',\
        'vegan',\
        'viridis',\
        'viridisLite',\
        'visNetwork',\
        'vtree',\
        'webshot',\
        'whisker',\
        'withr',\
        'WorldFlora',\
        'writexl',\
        'xfun',\
        'XML',\
        'xml2',\
        'xtable',\
        'xts',\
        'yaml',\
        'zeallot',\
        'zoo'\
    ), repos='http://r-proxy:8180/')"

apt-get -y clean
apt-get -y autoremove
